name: jupytext-syncher

# Only run this when the master branch changes
on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
       

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  jupytext-synch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install jupytext
        #pip install -r requirements.txt
    # Synch Jupytext files
    - name: jupytext sync
      run: |
        jupytext --set-formats ipynb,.md//md notebooks/*.ipynb
        jupytext --sync notebooks/*.ipynb
        jupytext --sync notebooks/.md/*.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply jupytext synch